# Generated by Django 2.2 on 2023-09-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20230921_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataid', models.CharField(default='', max_length=30)),
                ('temptime', models.DateTimeField(auto_now=True)),
                ('productid', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
