# Generated by Django 2.2 on 2023-09-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='datainfo',
            field=models.CharField(default='', max_length=3, verbose_name='补充信息'),
        ),
    ]
