# Generated by Django 2.2 on 2023-09-21 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_myuser_datainfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name_plural': '用户信息'},
        ),
    ]
